title:            "My Name is Toomee"
description:      "Blog posts, notes, and anecdotes about a kid with Duchenne Muscular Dystrophy."
disqus_shortname: 
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:              //talen-c.github.io

# Owner/author information
owner:
  name:           "Chad"
  avatar:         avatar.jpg
  bio:            "I'm just a dad."
  email:          you@email.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        talendmd
  facebook:       
  github:         talen-c
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +111420584891014438064

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
#pygments:    true
markdown:    kramdown

# Amount of posts to show on home page
paginate: 5


# Site settings
#title: Your awesome title
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

#testing collections
collections:
  - clinicals
#    output: true

# Build settings
#markdown: kramdown

#gems
gems:         'jekyll-paginate', group: :jekyll_plugins
